---
docker_user: "{{ dev_user }}"

docker_root_dir: "/srv/docker"

docker_directories:
  - "{{ docker_root_dir }}"
  - "{{ docker_root_dir }}/appdata"
  - "{{ docker_root_dir }}/compose"
  - "{{ docker_root_dir }}/backup-staging"

docker_apt_arch: "amd64"

docker_ce_version: "5:29.7.2-1~ubuntu.26.04~resolute"
docker_containerd_version: "2.3.3-1~ubuntu.26.04~resolute"
docker_buildx_version: "0.36.1-1~ubuntu.26.04~resolute"
docker_compose_version: "5.4.0-1~ubuntu.26.04~resolute"

docker_packages:
  - "docker-ce={{ docker_ce_version }}"
  - "docker-ce-cli={{ docker_ce_version }}"
  - "containerd.io={{ docker_containerd_version }}"
  - "docker-buildx-plugin={{ docker_buildx_version }}"
  - "docker-compose-plugin={{ docker_compose_version }}"

docker_conflicting_packages:
  - docker.io
  - docker-compose
  - docker-compose-v2
  - docker-doc
  - docker-buildx
  - podman-docker
  - containerd
  - runc
