---
all:
  vars:
    ansible_user: tuero

  children:
    gpu_servers:
      hosts:
        gpu-server:
          ansible_host: 10.0.0.111

    infra_servers:
      hosts:
        infra:
          ansible_host: 10.0.0.112

    services_servers:
      hosts:
        services:
          ansible_host: 10.0.0.113
