FROM caddy:{{ caddy_version }}-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare@{{ caddy_cloudflare_module_version }}

FROM caddy:{{ caddy_version }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
